language: java  
jdk:  
#  - oraclejdk7  
#  - openjdk7  
  - openjdk8  
before_install:  
   - "echo Preparing package"  
   - mvn clean package -Dmaven.test.skip=true -Dmaven.javadoc.skip=true  
install:  
  - "echo skipped"
script:  
#  - "echo skipped"   
  - mvn install -Dmaven.test.skip=true -Dmaven.javadoc.skip=true  
# - mvn deploy  
notifications:  
  email:  
    recipients:  
      - bungder@126.com
    #on_success: [always|never|change]  default: change  
    #on_failure: [always|never|change]  default: always  
